/*
 * LinkArrangementScalarEvaluator.h
 *
 *  Created on: May 24, 2017
 *      Author: kiet
 */

#ifndef LINKARRANGEMENTOPTIMIZATION_LINKARRANGEMENTSCALAREVALUATOR_H_
#define LINKARRANGEMENTOPTIMIZATION_LINKARRANGEMENTSCALAREVALUATOR_H_

#include <openea/EA.h>
#include "LinkArrangementDecoder.h"

/**
 * \ingroup linkarrangement
 *
 * \brief Evaluate network instances by running pre-defined events.
 *
 * Events can be read from file (user-defined) or generated by this class (number of computers is required).
 * There are two constructors for these two options.
 *
 * In this scalar evaluator, the fitness value of each network instance is a floating point
 * number (double data type in C++). This value is computed from the amount of delivered data
 * and cost, details can be found in DoScalarEvaluate().
 *
 * \see DoScalarEvaluate()
 */
class LinkArrangementScalarEvaluator: public ea::ScalarEvaluator {
public:
	EA_TYPEINFO_CUSTOM_DECL;

	LinkArrangementScalarEvaluator(std::string eventFile,double p_budget);
	LinkArrangementScalarEvaluator(uint numComputers, double budget);
	virtual ~LinkArrangementScalarEvaluator();

	virtual inline bool IsMaximizer() {
		return true;
	}

protected:
	virtual double DoScalarEvaluate(const ea::GenomePtr& pGenome) override;

private:
	std::string eventFile;
	long numComputers = -1;
	double budget = -1;

	LinkArrangementDecoder decoder;
	uint filenameCounter = 0;
};

REGISTER_ADDON(LinkArrangementScalarEvaluator)

#endif /* LINKARRANGEMENTOPTIMIZATION_LINKARRANGEMENTSCALAREVALUATOR_H_ */
